export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CHANGE_TRANSFER_COUNT = "CHANGE_TRANSFER_COUNT";
export const CHANGE_LIMIT = "CHANGE_LIMIT";
export const CHANGE_OFFSET = "CHANGE_OFFSET";
export const CHANGE_ORDER_FILTER = "CHANGE_ORDER_FILTER";
export const CLEAR_FILTERS = "CLEAR_FILTERS";